//! Jobs on hidden Airflow (REQ-38..42). Pebbles workflows are JSON records that
//! COMPILE to generated DAG files; the generated tasks call `pebbles_operator.py`,
//! which executes everything through pebblesd sessions as the workflow owner
//! (REQ-41). Airflow runs on the main, supervised by pebblesd, bound to localhost,
//! and never surfaces to users — the Jobs UI is the only face (REQ-38). Run state
//! comes from Airflow's metadata DB (read-only); logs from its log files.

use serde::{Deserialize, Serialize};
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub const AIRFLOW_BIN: &str = "/opt/pebbles/airflow/.venv/bin/airflow";
pub const OPERATOR_SRC: &str = "/opt/pebbles/airflow-support/pebbles_operator.py";
pub const AIRFLOW_USER: &str = "pebbles-airflow";
pub const AIRFLOW_DB: &str = "airflow";

#[derive(Debug, Error)]
pub enum JobsError {
    #[error("invalid workflow name {0:?}: must match [a-z][a-z0-9_-]{{0,47}}")]
    InvalidName(String),
    #[error("invalid task {0:?}: type must be sql|python|r|shell|notebook and ids unique")]
    InvalidTask(String),
    #[error("workflow {0:?} not found")]
    NotFound(String),
    #[error("a job named {0:?} already belongs to another user")]
    Owned(String),
    #[error("airflow is not available on this container")]
    NoAirflow,
    #[error("airflow command failed: {0}")]
    Airflow(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTask {
    pub id: String,
    /// sql | python | r | shell | notebook
    pub task_type: String,
    pub payload: String,
    #[serde(default)]
    pub engine: Option<String>,
    #[serde(default)]
    pub catalog: Option<String>,
    /// shared (default) or dedicated (REQ-39 session mode).
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub depends_on: Vec<String>,
    #[serde(default)]
    pub retries: Option<u32>,
    /// REQ-37: when set, `payload` is a PATH inside `~/repos/<repo>` and the
    /// task executes that file's content at `ref` (default HEAD) — resolved to
    /// a commit sha at run time and read via `git show`, never a checkout.
    #[serde(default)]
    pub repo: Option<String>,
    #[serde(default, rename = "ref")]
    pub git_ref: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Workflow {
    pub name: String,
    /// The owning user: every task runs under this identity (REQ-41).
    pub username: String,
    /// Cron expression, or null for manual-only (REQ-40 subset).
    #[serde(default)]
    pub schedule: Option<String>,
    pub tasks: Vec<WorkflowTask>,
}

fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 48
        && name.chars().next().is_some_and(|c| c.is_ascii_lowercase())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-')
}

pub fn airflow_home(config_dir: &Path) -> PathBuf {
    config_dir.join("airflow")
}

fn jobs_dir(config_dir: &Path) -> PathBuf {
    config_dir.join("jobs")
}

/// Python-literal string (the payloads go into a generated .py file).
fn py_str(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "")
    )
}

fn dag_id(name: &str) -> String {
    format!("pb_{}", name.replace('-', "_"))
}

/// Compile a workflow to its DAG file (REQ-38): the whole user-facing model
/// reduces to PythonOperator tasks bound to `run_pebbles_task`.
fn render_dag(wf: &Workflow) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by pebblesd — do not edit; the source of truth is jobs/{}.json\n\
         import pendulum\n\
         from airflow import DAG\n\
         from airflow.operators.python import PythonOperator\n\
         from pebbles_operator import run_pebbles_task\n\n\
         with DAG(\n    dag_id={},\n    schedule={},\n    start_date=pendulum.datetime(2026, 1, 1, tz=\"UTC\"),\n    catchup=False,\n) as dag:\n",
        wf.name,
        py_str(&dag_id(&wf.name)),
        wf.schedule
            .as_ref()
            .map(|s| py_str(s))
            .unwrap_or_else(|| "None".to_string()),
    ));
    for task in &wf.tasks {
        out.push_str(&format!(
            "    t_{id} = PythonOperator(\n        task_id={tid},\n        python_callable=run_pebbles_task,\n        retries={retries},\n        op_kwargs={{\n            \"username\": {user},\n            \"task_type\": {ttype},\n            \"payload\": {payload},\n            \"engine\": {engine},\n            \"catalog\": {catalog},\n            \"mode\": {mode},\n            \"repo\": {repo},\n            \"ref\": {git_ref},\n        }},\n    )\n",
            id = task.id.replace('-', "_"),
            tid = py_str(&task.id),
            retries = task.retries.unwrap_or(0),
            user = py_str(&wf.username),
            ttype = py_str(&task.task_type),
            payload = py_str(&task.payload),
            engine = task
                .engine
                .as_ref()
                .map(|e| py_str(e))
                .unwrap_or_else(|| "None".into()),
            catalog = task
                .catalog
                .as_ref()
                .map(|c| py_str(c))
                .unwrap_or_else(|| "None".into()),
            mode = py_str(task.mode.as_deref().unwrap_or("shared")),
            repo = task
                .repo
                .as_ref()
                .map(|r| py_str(r))
                .unwrap_or_else(|| "None".into()),
            git_ref = task
                .git_ref
                .as_ref()
                .map(|r| py_str(r))
                .unwrap_or_else(|| "None".into()),
        ));
    }
    for task in &wf.tasks {
        for dep in &task.depends_on {
            out.push_str(&format!(
                "    t_{} >> t_{}\n",
                dep.replace('-', "_"),
                task.id.replace('-', "_")
            ));
        }
    }
    out
}

pub fn validate(wf: &Workflow) -> Result<(), JobsError> {
    if !valid_name(&wf.name) {
        return Err(JobsError::InvalidName(wf.name.clone()));
    }
    let mut seen = std::collections::HashSet::new();
    for task in &wf.tasks {
        let type_ok = matches!(
            task.task_type.as_str(),
            "sql" | "python" | "r" | "shell" | "notebook"
        );
        if !valid_name(&task.id) || !type_ok || !seen.insert(&task.id) {
            return Err(JobsError::InvalidTask(task.id.clone()));
        }
        // REQ-37 repo refs: repo must look like a repo name; the ref must be a
        // plausible git rev with no room for argument injection (leading '-')
        // and no quotes that could escape the generated Python.
        if let Some(repo) = &task.repo {
            if !valid_name(repo) {
                return Err(JobsError::InvalidTask(format!(
                    "{}: invalid repo {repo:?}",
                    task.id
                )));
            }
        }
        if let Some(git_ref) = &task.git_ref {
            let ref_ok = task.repo.is_some()
                && !git_ref.is_empty()
                && git_ref.len() <= 128
                && !git_ref.starts_with('-')
                && git_ref
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '/' | '-'));
            if !ref_ok {
                return Err(JobsError::InvalidTask(format!(
                    "{}: invalid ref {git_ref:?}",
                    task.id
                )));
            }
        }
    }
    for task in &wf.tasks {
        for dep in &task.depends_on {
            if !seen.contains(dep) {
                return Err(JobsError::InvalidTask(format!(
                    "{}: unknown dependency {dep:?}",
                    task.id
                )));
            }
        }
    }
    Ok(())
}

/// Persist the workflow and (re)compile its DAG file.
pub fn save(config_dir: &Path, wf: &Workflow) -> Result<(), JobsError> {
    validate(wf)?;
    // Job names are global (they become Airflow DAG ids): never let one user's
    // save silently replace another user's job — it would then run as them.
    if let Ok(existing) = get(config_dir, &wf.name) {
        if existing.username != wf.username {
            return Err(JobsError::Owned(wf.name.clone()));
        }
    }
    let jobs = jobs_dir(config_dir);
    std::fs::create_dir_all(&jobs)?;
    std::fs::write(
        jobs.join(format!("{}.json", wf.name)),
        serde_json::to_string_pretty(wf).expect("serializable"),
    )?;
    let dags = airflow_home(config_dir).join("dags");
    std::fs::create_dir_all(&dags)?;
    std::fs::write(
        dags.join(format!("{}.py", dag_id(&wf.name))),
        render_dag(wf),
    )?;
    Ok(())
}

pub fn list(config_dir: &Path) -> Result<Vec<Workflow>, JobsError> {
    let mut flows = Vec::new();
    let Ok(entries) = std::fs::read_dir(jobs_dir(config_dir)) else {
        return Ok(flows);
    };
    for entry in entries.flatten() {
        if let Ok(content) = std::fs::read_to_string(entry.path()) {
            if let Ok(wf) = serde_json::from_str::<Workflow>(&content) {
                flows.push(wf);
            }
        }
    }
    flows.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(flows)
}

pub fn get(config_dir: &Path, name: &str) -> Result<Workflow, JobsError> {
    if !valid_name(name) {
        return Err(JobsError::InvalidName(name.to_string()));
    }
    let content = std::fs::read_to_string(jobs_dir(config_dir).join(format!("{name}.json")))
        .map_err(|_| JobsError::NotFound(name.to_string()))?;
    serde_json::from_str(&content).map_err(|_| JobsError::NotFound(name.to_string()))
}

fn read_secret(home: &Path, file: &str) -> String {
    std::fs::read_to_string(home.join(file))
        .unwrap_or_default()
        .trim()
        .to_string()
}

fn airflow_env(config_dir: &Path) -> Vec<(String, String)> {
    let home = airflow_home(config_dir);
    // Airflow 2.10 LocalExecutor: the scheduler runs tasks as direct subprocesses
    // against the metadata DB — no execution API, no JWT. A stable Fernet key is
    // still shared so encrypted connections/variables survive restarts.
    let fernet = read_secret(&home, "fernet-key");
    vec![
        ("HOME".into(), home.display().to_string()),
        ("AIRFLOW_HOME".into(), home.display().to_string()),
        // `airflow_cli` runs this env after env_clear(): restore the UTF-8 locale
        // there too (the supervised scheduler inherits pebblesd's C.UTF-8 anyway).
        // Same landmine as initdb-on-Incus: a C/ASCII locale turns the first
        // non-ASCII byte into a crash deep inside Airflow.
        ("LANG".into(), "C.UTF-8".into()),
        ("LC_ALL".into(), "C.UTF-8".into()),
        ("PYTHONUTF8".into(), "1".into()),
        ("AIRFLOW__CORE__FERNET_KEY".into(), fernet),
        (
            "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN".into(),
            format!("postgresql+psycopg2://{AIRFLOW_USER}@/{AIRFLOW_DB}?host=/run/postgresql"),
        ),
        ("AIRFLOW__CORE__EXECUTOR".into(), "LocalExecutor".into()),
        ("AIRFLOW__CORE__LOAD_EXAMPLES".into(), "False".into()),
        // New DAGs are live the moment they're saved (else triggered runs queue).
        (
            "AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION".into(),
            "False".into(),
        ),
        (
            "AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL".into(),
            "10".into(),
        ),
        (
            "PATH".into(),
            "/opt/pebbles/airflow/.venv/bin:/usr/local/bin:/usr/bin:/bin".into(),
        ),
        ("PEBBLES_SOCKET".into(), "/run/pebbles/pebblesd.sock".into()),
    ]
}

/// Filesystem-side Airflow provisioning (idempotent, needs NO postgres): dirs,
/// the operator on the DAG import path, the JWT secret. Returns the service env.
/// The Postgres role/database/migrations run as supervised pre-steps that wait
/// for the socket — postgres isn't up yet when services are constructed.
pub fn prepare_fs(config_dir: &Path) -> Result<Vec<(String, String)>, JobsError> {
    use std::os::unix::fs::PermissionsExt;
    if !Path::new(AIRFLOW_BIN).exists() {
        return Err(JobsError::NoAirflow);
    }
    let (uid, gid) = pebbles_identity::system_user(AIRFLOW_USER).ok_or(JobsError::NoAirflow)?;
    let home = airflow_home(config_dir);
    let dags = home.join("dags");
    std::fs::create_dir_all(&dags)?;
    // The operator ships in the image; the dags dir is on the import path.
    std::fs::copy(OPERATOR_SRC, dags.join("pebbles_operator.py"))?;

    // Stable Fernet key (url-safe base64 of 32 bytes), created once and reused so
    // encrypted connections/variables survive restarts and upgrades.
    let fernet_path = home.join("fernet-key");
    if !fernet_path.exists() {
        std::fs::write(&fernet_path, fernet_key())?;
        std::fs::set_permissions(&fernet_path, std::fs::Permissions::from_mode(0o600))?;
    }
    std::os::unix::fs::chown(&fernet_path, Some(uid), Some(gid))?;
    for dir in [&home, &dags, &home.join("logs")] {
        std::fs::create_dir_all(dir)?;
        std::os::unix::fs::chown(dir, Some(uid), Some(gid))?;
    }
    Ok(airflow_env(config_dir))
}

/// A valid Fernet key: url-safe base64 of 32 random bytes (44 chars, '='-padded).
fn fernet_key() -> String {
    use std::io::Read;
    const T: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let mut raw = [0u8; 32];
    std::fs::File::open("/dev/urandom")
        .and_then(|mut f| f.read_exact(&mut raw))
        .expect("/dev/urandom");
    let mut out = String::new();
    for chunk in raw.chunks(3) {
        let b = [
            chunk[0],
            *chunk.get(1).unwrap_or(&0),
            *chunk.get(2).unwrap_or(&0),
        ];
        out.push(T[(b[0] >> 2) as usize] as char);
        out.push(T[(((b[0] & 3) << 4) | (b[1] >> 4)) as usize] as char);
        out.push(if chunk.len() > 1 {
            T[(((b[1] & 15) << 2) | (b[2] >> 6)) as usize] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            T[(b[2] & 63) as usize] as char
        } else {
            '='
        });
    }
    out
}

/// `sh -c` one-liner that waits for the Postgres socket (pre-step material).
pub const WAIT_PG_SH: &str = "for i in $(seq 1 120); do \
    [ -S /run/postgresql/.s.PGSQL.5432 ] && exit 0; sleep 1; done; \
    echo 'postgres never came up' >&2; exit 1";

/// Idempotent, RACE-PROOF role + database provisioning, run AS the postgres user.
/// Attempt the create, ignore the duplicate error, then verify existence — never
/// check-then-create. The whole thing RETRIES: the socket existing (WAIT_PG_SH)
/// does not mean postgres accepts connections yet — after an unclean shutdown it
/// answers "the database system is starting up" through crash recovery, and a
/// single-shot pre-step failure would disable the Airflow service for the whole
/// boot (supervisor pre-steps don't restart).
pub const PROVISION_SH: &str = r#"for i in $(seq 1 90); do
  psql -h /run/postgresql -d postgres -c "CREATE ROLE \"pebbles-airflow\" LOGIN" 2>/dev/null
  psql -h /run/postgresql -d postgres -c "CREATE DATABASE airflow OWNER \"pebbles-airflow\"" 2>/dev/null
  psql -h /run/postgresql -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='pebbles-airflow'" 2>/dev/null | grep -q 1 \
    && psql -h /run/postgresql -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='airflow'" 2>/dev/null | grep -q 1 \
    && exit 0
  sleep 2
done
echo 'airflow provisioning never succeeded: postgres never accepted the role/database' >&2
exit 1"#;

/// `airflow db migrate` with retries (concurrent first-boot services and a
/// just-created database make one-shot migration brittle).
pub const MIGRATE_SH: &str = "for i in $(seq 1 10); do \
    /opt/pebbles/airflow/.venv/bin/airflow db migrate && exit 0; sleep 5; done; exit 1";

/// Run an airflow CLI command as the airflow user; returns stdout. Hard 60 s
/// wall-clock cap — a hung CLI must never wedge an API handler (or CI).
pub fn airflow_cli(config_dir: &Path, args: &[&str]) -> Result<String, JobsError> {
    let (uid, gid) = pebbles_identity::system_user(AIRFLOW_USER).ok_or(JobsError::NoAirflow)?;
    let mut cmd = std::process::Command::new("timeout");
    cmd.arg("60").arg(AIRFLOW_BIN).args(args).env_clear();
    for (k, v) in airflow_env(config_dir) {
        cmd.env(k, v);
    }
    if uid != unsafe { libc::geteuid() } {
        cmd.uid(uid).gid(gid);
    }
    let out = cmd
        .output()
        .map_err(|e| JobsError::Airflow(e.to_string()))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        Err(JobsError::Airflow(
            String::from_utf8_lossy(&out.stderr)
                .lines()
                .rev()
                .take(5)
                .collect::<Vec<_>>()
                .join(" | "),
        ))
    }
}

pub fn trigger(config_dir: &Path, name: &str) -> Result<(), JobsError> {
    get(config_dir, name)?;
    let dag = dag_id(name);
    match airflow_cli(config_dir, &["dags", "trigger", &dag]) {
        Ok(_) => Ok(()),
        // A job saved seconds ago isn't in Airflow's DagModel until the
        // scheduler's next directory scan (~10 s). Register just this file
        // ourselves and retry once — "Run now" right after "Save" must work.
        Err(JobsError::Airflow(msg)) if is_dag_not_found(&msg) => {
            let file = airflow_home(config_dir)
                .join("dags")
                .join(format!("{dag}.py"));
            airflow_cli(
                config_dir,
                &["dags", "reserialize", "-S", &file.display().to_string()],
            )?;
            airflow_cli(config_dir, &["dags", "trigger", &dag])
                .map(|_| ())
                .map_err(|_| {
                    JobsError::Airflow(
                        "the scheduler hasn't registered this job yet — try again in a few seconds"
                            .into(),
                    )
                })
        }
        Err(e) => Err(e),
    }
}

fn is_dag_not_found(msg: &str) -> bool {
    msg.contains("DagNotFound") || msg.contains("not found in DagModel")
}

#[derive(Debug, Clone, Serialize)]
pub struct RunInfo {
    pub run_id: String,
    pub state: String,
    pub start: String,
    pub end: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct TaskRunInfo {
    pub task_id: String,
    pub state: String,
    pub start: String,
    pub end: String,
    pub log: String,
}

/// Run history from Airflow's metadata DB (read-only, REQ-42).
pub fn runs(config_dir: &Path, name: &str) -> Result<Vec<RunInfo>, JobsError> {
    get(config_dir, name)?;
    let out = crate::catalog::psql_in(
        AIRFLOW_DB,
        &format!(
            "SELECT run_id || '|' || state || '|' || coalesce(start_date::text,'') || '|' || \
             coalesce(end_date::text,'') FROM dag_run WHERE dag_id = '{}' \
             ORDER BY id DESC LIMIT 25;",
            dag_id(name)
        ),
    )
    .map_err(|e| JobsError::Airflow(e.to_string()))?;
    Ok(out
        .lines()
        .filter_map(|line| {
            let mut f = line.trim().splitn(4, '|');
            Some(RunInfo {
                run_id: f.next()?.to_string(),
                state: f.next()?.to_string(),
                start: f.next().unwrap_or("").to_string(),
                end: f.next().unwrap_or("").to_string(),
            })
        })
        .collect())
}

pub fn run_detail(
    config_dir: &Path,
    name: &str,
    run_id: &str,
) -> Result<Vec<TaskRunInfo>, JobsError> {
    get(config_dir, name)?;
    if run_id.contains('\'') {
        return Err(JobsError::InvalidName(run_id.to_string()));
    }
    let dag = dag_id(name);
    let out = crate::catalog::psql_in(
        AIRFLOW_DB,
        &format!(
            "SELECT task_id || '|' || coalesce(state,'') || '|' || coalesce(start_date::text,'') \
             || '|' || coalesce(end_date::text,'') || '|' || coalesce(try_number::text,'1') \
             FROM task_instance WHERE dag_id = '{dag}' AND run_id = '{run_id}' ORDER BY task_id;"
        ),
    )
    .map_err(|e| JobsError::Airflow(e.to_string()))?;
    Ok(out
        .lines()
        .filter_map(|line| {
            let mut f = line.trim().splitn(5, '|');
            let task_id = f.next()?.to_string();
            let state = f.next()?.to_string();
            let start = f.next().unwrap_or("").to_string();
            let end = f.next().unwrap_or("").to_string();
            let attempt: u32 = f.next().unwrap_or("1").parse().unwrap_or(1);
            let log_path = airflow_home(config_dir).join(format!(
                "logs/dag_id={dag}/run_id={run_id}/task_id={task_id}/attempt={attempt}.log"
            ));
            let mut log = std::fs::read_to_string(log_path).unwrap_or_default();
            if log.len() > 65536 {
                log = log[log.len() - 65536..].to_string();
            }
            Some(TaskRunInfo {
                task_id,
                state,
                start,
                end,
                log,
            })
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn flow() -> Workflow {
        Workflow {
            name: "nightly-claims".into(),
            username: "maya".into(),
            schedule: Some("0 2 * * *".into()),
            tasks: vec![
                WorkflowTask {
                    id: "load".into(),
                    task_type: "sql".into(),
                    payload: "SELECT 1;".into(),
                    engine: None,
                    catalog: Some("claims".into()),
                    mode: None,
                    depends_on: vec![],
                    retries: Some(1),
                    repo: None,
                    git_ref: None,
                },
                WorkflowTask {
                    id: "report".into(),
                    task_type: "notebook".into(),
                    payload: "claims-eda".into(),
                    engine: Some("worker-1".into()),
                    catalog: None,
                    mode: Some("dedicated".into()),
                    depends_on: vec!["load".into()],
                    retries: None,
                    repo: None,
                    git_ref: None,
                },
            ],
        }
    }

    #[test]
    fn workflows_compile_to_dags_with_dependencies_and_identity() {
        let dag = render_dag(&flow());
        assert!(dag.contains("dag_id=\"pb_nightly_claims\""));
        assert!(dag.contains("schedule=\"0 2 * * *\""));
        assert!(dag.contains("\"username\": \"maya\""));
        assert!(dag.contains("\"engine\": \"worker-1\""));
        assert!(dag.contains("\"mode\": \"dedicated\""));
        assert!(dag.contains("t_load >> t_report"));
    }

    #[test]
    fn validation_rejects_bad_names_types_and_dangling_deps() {
        let mut wf = flow();
        assert!(validate(&wf).is_ok());
        wf.tasks[0].task_type = "spark".into();
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
        let mut wf = flow();
        wf.tasks[1].depends_on = vec!["ghost".into()];
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
        let mut wf = flow();
        wf.name = "Bad Name".into();
        assert!(matches!(validate(&wf), Err(JobsError::InvalidName(_))));
    }

    #[test]
    fn fernet_key_is_44_char_urlsafe_base64() {
        let k = fernet_key();
        assert_eq!(k.len(), 44, "Fernet keys are 32 bytes → 44 base64 chars");
        assert!(k.ends_with('='));
        assert!(k
            .trim_end_matches('=')
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || c == b'-' || c == b'_'));
    }

    #[test]
    fn repo_ref_tasks_render_and_validate() {
        let mut wf = flow();
        wf.tasks[1].repo = Some("analytics".into());
        wf.tasks[1].git_ref = Some("v1.2".into());
        wf.tasks[1].payload = "pipelines/report.json".into();
        assert!(validate(&wf).is_ok());
        let dag = render_dag(&wf);
        assert!(dag.contains("\"repo\": \"analytics\""));
        assert!(dag.contains("\"ref\": \"v1.2\""));
        // tasks without a repo render explicit Nones (kwargs stay total)
        assert!(dag.contains("\"repo\": None"));

        // a ref without a repo is meaningless
        let mut wf = flow();
        wf.tasks[0].git_ref = Some("main".into());
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
        // leading '-' would read as a git flag — refused
        let mut wf = flow();
        wf.tasks[0].repo = Some("analytics".into());
        wf.tasks[0].git_ref = Some("--exec=evil".into());
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
        // quotes could escape the generated Python — refused by the charset
        let mut wf = flow();
        wf.tasks[0].repo = Some("analytics".into());
        wf.tasks[0].git_ref = Some("v1\"; import os".into());
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
        // repo names follow workflow naming
        let mut wf = flow();
        wf.tasks[0].repo = Some("Bad Repo".into());
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
    }

    #[test]
    fn saving_over_another_users_job_is_refused() {
        let dir = tempfile::tempdir().unwrap();
        let wf = flow();
        save(dir.path(), &wf).unwrap();
        save(dir.path(), &wf).unwrap(); // the owner may re-save
        let mut hijack = flow();
        hijack.username = "mallory".into();
        assert!(matches!(
            save(dir.path(), &hijack),
            Err(JobsError::Owned(_))
        ));
        assert_eq!(get(dir.path(), &wf.name).unwrap().username, "maya");
    }

    #[test]
    fn dag_not_found_is_recognised_for_the_register_and_retry_path() {
        assert!(is_dag_not_found(
            "airflow.exceptions.DagNotFound: Dag id pb_uat_job not found in DagModel"
        ));
        assert!(!is_dag_not_found(
            "psycopg2.OperationalError: could not connect"
        ));
    }

    #[test]
    fn payloads_escape_into_python_safely() {
        let s = py_str("SELECT \"a\"\nFROM 't';\\x");
        assert_eq!(s, "\"SELECT \\\"a\\\"\\nFROM 't';\\\\x\"");
    }
}
