//! Jobs on hidden Airflow (REQ-38..42). Pebbles workflows are JSON records that
//! COMPILE to generated DAG files; the generated tasks call `pebbles_operator.py`,
//! which executes everything through pebblesd sessions as the workflow owner
//! (REQ-41). Airflow runs on the main, supervised by pebblesd, bound to localhost,
//! and never surfaces to users — the Jobs UI is the only face (REQ-38). Run state
//! comes from Airflow's metadata DB (read-only); logs from its log files.

use serde::{Deserialize, Serialize};
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub const AIRFLOW_BIN: &str = "/opt/pebbles/airflow/.venv/bin/airflow";
pub const OPERATOR_SRC: &str = "/opt/pebbles/airflow-support/pebbles_operator.py";
pub const AIRFLOW_USER: &str = "pebbles-airflow";
pub const AIRFLOW_DB: &str = "airflow";
/// The internal execution API port — localhost only, never user-facing.
pub const API_PORT: u16 = 8793;

#[derive(Debug, Error)]
pub enum JobsError {
    #[error("invalid workflow name {0:?}: must match [a-z][a-z0-9_-]{{0,47}}")]
    InvalidName(String),
    #[error("invalid task {0:?}: type must be sql|python|r|shell|notebook and ids unique")]
    InvalidTask(String),
    #[error("workflow {0:?} not found")]
    NotFound(String),
    #[error("airflow is not available on this container")]
    NoAirflow,
    #[error("airflow command failed: {0}")]
    Airflow(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTask {
    pub id: String,
    /// sql | python | r | shell | notebook
    pub task_type: String,
    pub payload: String,
    #[serde(default)]
    pub engine: Option<String>,
    #[serde(default)]
    pub catalog: Option<String>,
    /// shared (default) or dedicated (REQ-39 session mode).
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub depends_on: Vec<String>,
    #[serde(default)]
    pub retries: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Workflow {
    pub name: String,
    /// The owning user: every task runs under this identity (REQ-41).
    pub username: String,
    /// Cron expression, or null for manual-only (REQ-40 subset).
    #[serde(default)]
    pub schedule: Option<String>,
    pub tasks: Vec<WorkflowTask>,
}

fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 48
        && name.chars().next().is_some_and(|c| c.is_ascii_lowercase())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-')
}

pub fn airflow_home(config_dir: &Path) -> PathBuf {
    config_dir.join("airflow")
}

fn jobs_dir(config_dir: &Path) -> PathBuf {
    config_dir.join("jobs")
}

/// Python-literal string (the payloads go into a generated .py file).
fn py_str(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "")
    )
}

fn dag_id(name: &str) -> String {
    format!("pb_{}", name.replace('-', "_"))
}

/// Compile a workflow to its DAG file (REQ-38): the whole user-facing model
/// reduces to PythonOperator tasks bound to `run_pebbles_task`.
fn render_dag(wf: &Workflow) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Generated by pebblesd — do not edit; the source of truth is jobs/{}.json\n\
         import pendulum\n\
         from airflow import DAG\n\
         from airflow.providers.standard.operators.python import PythonOperator\n\
         from pebbles_operator import run_pebbles_task\n\n\
         with DAG(\n    dag_id={},\n    schedule={},\n    start_date=pendulum.datetime(2026, 1, 1, tz=\"UTC\"),\n    catchup=False,\n) as dag:\n",
        wf.name,
        py_str(&dag_id(&wf.name)),
        wf.schedule
            .as_ref()
            .map(|s| py_str(s))
            .unwrap_or_else(|| "None".to_string()),
    ));
    for task in &wf.tasks {
        out.push_str(&format!(
            "    t_{id} = PythonOperator(\n        task_id={tid},\n        python_callable=run_pebbles_task,\n        retries={retries},\n        op_kwargs={{\n            \"username\": {user},\n            \"task_type\": {ttype},\n            \"payload\": {payload},\n            \"engine\": {engine},\n            \"catalog\": {catalog},\n            \"mode\": {mode},\n        }},\n    )\n",
            id = task.id.replace('-', "_"),
            tid = py_str(&task.id),
            retries = task.retries.unwrap_or(0),
            user = py_str(&wf.username),
            ttype = py_str(&task.task_type),
            payload = py_str(&task.payload),
            engine = task
                .engine
                .as_ref()
                .map(|e| py_str(e))
                .unwrap_or_else(|| "None".into()),
            catalog = task
                .catalog
                .as_ref()
                .map(|c| py_str(c))
                .unwrap_or_else(|| "None".into()),
            mode = py_str(task.mode.as_deref().unwrap_or("shared")),
        ));
    }
    for task in &wf.tasks {
        for dep in &task.depends_on {
            out.push_str(&format!(
                "    t_{} >> t_{}\n",
                dep.replace('-', "_"),
                task.id.replace('-', "_")
            ));
        }
    }
    out
}

pub fn validate(wf: &Workflow) -> Result<(), JobsError> {
    if !valid_name(&wf.name) {
        return Err(JobsError::InvalidName(wf.name.clone()));
    }
    let mut seen = std::collections::HashSet::new();
    for task in &wf.tasks {
        let type_ok = matches!(
            task.task_type.as_str(),
            "sql" | "python" | "r" | "shell" | "notebook"
        );
        if !valid_name(&task.id) || !type_ok || !seen.insert(&task.id) {
            return Err(JobsError::InvalidTask(task.id.clone()));
        }
    }
    for task in &wf.tasks {
        for dep in &task.depends_on {
            if !seen.contains(dep) {
                return Err(JobsError::InvalidTask(format!(
                    "{}: unknown dependency {dep:?}",
                    task.id
                )));
            }
        }
    }
    Ok(())
}

/// Persist the workflow and (re)compile its DAG file.
pub fn save(config_dir: &Path, wf: &Workflow) -> Result<(), JobsError> {
    validate(wf)?;
    let jobs = jobs_dir(config_dir);
    std::fs::create_dir_all(&jobs)?;
    std::fs::write(
        jobs.join(format!("{}.json", wf.name)),
        serde_json::to_string_pretty(wf).expect("serializable"),
    )?;
    let dags = airflow_home(config_dir).join("dags");
    std::fs::create_dir_all(&dags)?;
    std::fs::write(
        dags.join(format!("{}.py", dag_id(&wf.name))),
        render_dag(wf),
    )?;
    Ok(())
}

pub fn list(config_dir: &Path) -> Result<Vec<Workflow>, JobsError> {
    let mut flows = Vec::new();
    let Ok(entries) = std::fs::read_dir(jobs_dir(config_dir)) else {
        return Ok(flows);
    };
    for entry in entries.flatten() {
        if let Ok(content) = std::fs::read_to_string(entry.path()) {
            if let Ok(wf) = serde_json::from_str::<Workflow>(&content) {
                flows.push(wf);
            }
        }
    }
    flows.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(flows)
}

pub fn get(config_dir: &Path, name: &str) -> Result<Workflow, JobsError> {
    if !valid_name(name) {
        return Err(JobsError::InvalidName(name.to_string()));
    }
    let content = std::fs::read_to_string(jobs_dir(config_dir).join(format!("{name}.json")))
        .map_err(|_| JobsError::NotFound(name.to_string()))?;
    serde_json::from_str(&content).map_err(|_| JobsError::NotFound(name.to_string()))
}

fn airflow_env(config_dir: &Path) -> Vec<(String, String)> {
    let home = airflow_home(config_dir);
    let jwt = std::fs::read_to_string(home.join("jwt-secret"))
        .unwrap_or_default()
        .trim()
        .to_string();
    vec![
        ("HOME".into(), home.display().to_string()),
        ("AIRFLOW_HOME".into(), home.display().to_string()),
        (
            "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN".into(),
            format!("postgresql+psycopg2://{AIRFLOW_USER}@/{AIRFLOW_DB}?host=/run/postgresql"),
        ),
        ("AIRFLOW__CORE__EXECUTOR".into(), "LocalExecutor".into()),
        ("AIRFLOW__CORE__LOAD_EXAMPLES".into(), "False".into()),
        // Pebbles workflows are live the moment they're saved; without this, new
        // DAGs are born paused and triggered runs sit queued forever.
        (
            "AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION".into(),
            "False".into(),
        ),
        (
            "AIRFLOW__CORE__EXECUTION_API_SERVER_URL".into(),
            format!("http://127.0.0.1:{API_PORT}/execution/"),
        ),
        (
            "AIRFLOW__CORE__AUTH_MANAGER".into(),
            "airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager".into(),
        ),
        (
            "AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS".into(),
            "True".into(),
        ),
        ("AIRFLOW__API_AUTH__JWT_SECRET".into(), jwt),
        (
            "AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL".into(),
            "10".into(),
        ),
        (
            "AIRFLOW__DAG_PROCESSOR__REFRESH_INTERVAL".into(),
            "10".into(),
        ),
        (
            "PATH".into(),
            "/opt/pebbles/airflow/.venv/bin:/usr/local/bin:/usr/bin:/bin".into(),
        ),
        ("PEBBLES_SOCKET".into(), "/run/pebbles/pebblesd.sock".into()),
    ]
}

/// Filesystem-side Airflow provisioning (idempotent, needs NO postgres): dirs,
/// the operator on the DAG import path, the JWT secret. Returns the service env.
/// The Postgres role/database/migrations run as supervised pre-steps that wait
/// for the socket — postgres isn't up yet when services are constructed.
pub fn prepare_fs(config_dir: &Path) -> Result<Vec<(String, String)>, JobsError> {
    use std::os::unix::fs::PermissionsExt;
    if !Path::new(AIRFLOW_BIN).exists() {
        return Err(JobsError::NoAirflow);
    }
    let (uid, gid) = pebbles_identity::system_user(AIRFLOW_USER).ok_or(JobsError::NoAirflow)?;
    let home = airflow_home(config_dir);
    let dags = home.join("dags");
    std::fs::create_dir_all(&dags)?;
    // The operator ships in the image; the dags dir is on the import path.
    std::fs::copy(OPERATOR_SRC, dags.join("pebbles_operator.py"))?;
    let jwt_path = home.join("jwt-secret");
    if !jwt_path.exists() {
        std::fs::write(&jwt_path, crate::cluster::random_hex(32))?;
        std::fs::set_permissions(&jwt_path, std::fs::Permissions::from_mode(0o600))?;
    }
    for dir in [&home, &dags, &home.join("logs")] {
        std::fs::create_dir_all(dir)?;
        std::os::unix::fs::chown(dir, Some(uid), Some(gid))?;
    }
    std::os::unix::fs::chown(&jwt_path, Some(uid), Some(gid))?;
    Ok(airflow_env(config_dir))
}

/// `sh -c` one-liner that waits for the Postgres socket (pre-step material).
pub const WAIT_PG_SH: &str = "for i in $(seq 1 120); do \
    [ -S /run/postgresql/.s.PGSQL.5432 ] && exit 0; sleep 1; done; \
    echo 'postgres never came up' >&2; exit 1";

/// Idempotent, RACE-PROOF role + database provisioning, run AS the postgres user.
/// Three services run this concurrently at boot: attempt the create, ignore the
/// duplicate error, then verify existence — never check-then-create.
pub const PROVISION_SH: &str = r#"psql -h /run/postgresql -d postgres -c "CREATE ROLE \"pebbles-airflow\" LOGIN" 2>/dev/null; psql -h /run/postgresql -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='pebbles-airflow'" | grep -q 1 || exit 1; psql -h /run/postgresql -d postgres -c "CREATE DATABASE airflow OWNER \"pebbles-airflow\"" 2>/dev/null; psql -h /run/postgresql -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='airflow'" | grep -q 1"#;

/// `airflow db migrate` with retries (concurrent first-boot services and a
/// just-created database make one-shot migration brittle).
pub const MIGRATE_SH: &str = "for i in $(seq 1 10); do \
    /opt/pebbles/airflow/.venv/bin/airflow db migrate && exit 0; sleep 5; done; exit 1";

/// Run an airflow CLI command as the airflow user; returns stdout.
pub fn airflow_cli(config_dir: &Path, args: &[&str]) -> Result<String, JobsError> {
    let (uid, gid) = pebbles_identity::system_user(AIRFLOW_USER).ok_or(JobsError::NoAirflow)?;
    let mut cmd = std::process::Command::new(AIRFLOW_BIN);
    cmd.args(args).env_clear();
    for (k, v) in airflow_env(config_dir) {
        cmd.env(k, v);
    }
    if uid != unsafe { libc::geteuid() } {
        cmd.uid(uid).gid(gid);
    }
    let out = cmd
        .output()
        .map_err(|e| JobsError::Airflow(e.to_string()))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        Err(JobsError::Airflow(
            String::from_utf8_lossy(&out.stderr)
                .lines()
                .rev()
                .take(5)
                .collect::<Vec<_>>()
                .join(" | "),
        ))
    }
}

pub fn trigger(config_dir: &Path, name: &str) -> Result<(), JobsError> {
    get(config_dir, name)?;
    airflow_cli(config_dir, &["dags", "trigger", &dag_id(name)]).map(|_| ())
}

#[derive(Debug, Clone, Serialize)]
pub struct RunInfo {
    pub run_id: String,
    pub state: String,
    pub start: String,
    pub end: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct TaskRunInfo {
    pub task_id: String,
    pub state: String,
    pub start: String,
    pub end: String,
    pub log: String,
}

/// Run history from Airflow's metadata DB (read-only, REQ-42).
pub fn runs(config_dir: &Path, name: &str) -> Result<Vec<RunInfo>, JobsError> {
    get(config_dir, name)?;
    let out = crate::catalog::psql_in(
        AIRFLOW_DB,
        &format!(
            "SELECT run_id || '|' || state || '|' || coalesce(start_date::text,'') || '|' || \
             coalesce(end_date::text,'') FROM dag_run WHERE dag_id = '{}' \
             ORDER BY id DESC LIMIT 25;",
            dag_id(name)
        ),
    )
    .map_err(|e| JobsError::Airflow(e.to_string()))?;
    Ok(out
        .lines()
        .filter_map(|line| {
            let mut f = line.trim().splitn(4, '|');
            Some(RunInfo {
                run_id: f.next()?.to_string(),
                state: f.next()?.to_string(),
                start: f.next().unwrap_or("").to_string(),
                end: f.next().unwrap_or("").to_string(),
            })
        })
        .collect())
}

pub fn run_detail(
    config_dir: &Path,
    name: &str,
    run_id: &str,
) -> Result<Vec<TaskRunInfo>, JobsError> {
    get(config_dir, name)?;
    if run_id.contains('\'') {
        return Err(JobsError::InvalidName(run_id.to_string()));
    }
    let dag = dag_id(name);
    let out = crate::catalog::psql_in(
        AIRFLOW_DB,
        &format!(
            "SELECT task_id || '|' || coalesce(state,'') || '|' || coalesce(start_date::text,'') \
             || '|' || coalesce(end_date::text,'') || '|' || coalesce(try_number::text,'1') \
             FROM task_instance WHERE dag_id = '{dag}' AND run_id = '{run_id}' ORDER BY task_id;"
        ),
    )
    .map_err(|e| JobsError::Airflow(e.to_string()))?;
    Ok(out
        .lines()
        .filter_map(|line| {
            let mut f = line.trim().splitn(5, '|');
            let task_id = f.next()?.to_string();
            let state = f.next()?.to_string();
            let start = f.next().unwrap_or("").to_string();
            let end = f.next().unwrap_or("").to_string();
            let attempt: u32 = f.next().unwrap_or("1").parse().unwrap_or(1);
            let log_path = airflow_home(config_dir).join(format!(
                "logs/dag_id={dag}/run_id={run_id}/task_id={task_id}/attempt={attempt}.log"
            ));
            let mut log = std::fs::read_to_string(log_path).unwrap_or_default();
            if log.len() > 65536 {
                log = log[log.len() - 65536..].to_string();
            }
            Some(TaskRunInfo {
                task_id,
                state,
                start,
                end,
                log,
            })
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn flow() -> Workflow {
        Workflow {
            name: "nightly-claims".into(),
            username: "maya".into(),
            schedule: Some("0 2 * * *".into()),
            tasks: vec![
                WorkflowTask {
                    id: "load".into(),
                    task_type: "sql".into(),
                    payload: "SELECT 1;".into(),
                    engine: None,
                    catalog: Some("claims".into()),
                    mode: None,
                    depends_on: vec![],
                    retries: Some(1),
                },
                WorkflowTask {
                    id: "report".into(),
                    task_type: "notebook".into(),
                    payload: "claims-eda".into(),
                    engine: Some("worker-1".into()),
                    catalog: None,
                    mode: Some("dedicated".into()),
                    depends_on: vec!["load".into()],
                    retries: None,
                },
            ],
        }
    }

    #[test]
    fn workflows_compile_to_dags_with_dependencies_and_identity() {
        let dag = render_dag(&flow());
        assert!(dag.contains("dag_id=\"pb_nightly_claims\""));
        assert!(dag.contains("schedule=\"0 2 * * *\""));
        assert!(dag.contains("\"username\": \"maya\""));
        assert!(dag.contains("\"engine\": \"worker-1\""));
        assert!(dag.contains("\"mode\": \"dedicated\""));
        assert!(dag.contains("t_load >> t_report"));
    }

    #[test]
    fn validation_rejects_bad_names_types_and_dangling_deps() {
        let mut wf = flow();
        assert!(validate(&wf).is_ok());
        wf.tasks[0].task_type = "spark".into();
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
        let mut wf = flow();
        wf.tasks[1].depends_on = vec!["ghost".into()];
        assert!(matches!(validate(&wf), Err(JobsError::InvalidTask(_))));
        let mut wf = flow();
        wf.name = "Bad Name".into();
        assert!(matches!(validate(&wf), Err(JobsError::InvalidName(_))));
    }

    #[test]
    fn payloads_escape_into_python_safely() {
        let s = py_str("SELECT \"a\"\nFROM 't';\\x");
        assert_eq!(s, "\"SELECT \\\"a\\\"\\nFROM 't';\\\\x\"");
    }
}
